package:
  name: {{ environ.get('package_name', 'deepchem') }}
  version: "2.3.0"

source:
    git_url: https://github.com/deepchem/deepchem.git
    git_tag: 2.3.0

build:
  number: 0
  skip: True  # [win]


requirements:
  build:
    - python {{ python }}
    - setuptools
    - pbr
    - numpy

  run:
    - python {{ python }}
    - pdbfixer
    - mdtraj
    - joblib
    - scikit-learn
    - networkx
    - xgboost
    - pillow
    - pandas
    - {{ environ.get('tensorflow_enabled','tensorflow') }} ==1.14.0
    - zlib
    - requests
    - simdna
    - jupyter
    - rdkit


about:
  home: https://github.com/deepchem/deepchem
  license: MIT
  summary: 'Deep-learning models for Drug Discovery and Quantum Chemistry '
  description: |
    DeepChem aims to provide a high quality open-source toolchain that
    democratizes the use of deep-learning in drug discovery, materials
    science, quantum chemistry, and biology.
  doc_url: https://deepchem.io/
  dev_url: https:/github.com/deepchem/deepchem
